-- Seed dos itens (base mestre Colibri). Rode DEPOIS do schema.sql
TRUNCATE items RESTART IDENTITY CASCADE;
INSERT INTO items (codigo, nome, classificacao, setor, unidade, custo) VALUES
('822','baldinho de praia mp','COZINHA','Recepção/Estoque Central','UND',6.8),
('618','barriga mp','COZINHA','Congelada Cozinha','KG',26.98),
('617','bisteca de lombo mp','COZINHA','Congelada Cozinha','KG',18.6),
('604','carne moida mp','COZINHA','Congelada Cozinha','KG',31.2),
('613','carne seca mp','COZINHA','Congelada Cozinha','KG',46.9611),
('696','coração de alcatra mp','COZINHA','Congelada Cozinha','KG',36.2),
('605','costela boi sem osso mp','COZINHA','Congelada Cozinha','KG',27.4),
('615','costelinha suina salgada mp','COZINHA','Congelada Cozinha','KG',28.9685),
('606','coxa sobrecoxa com osso mp','COZINHA','Congelada Cozinha','KG',6.7),
('1571','cupim bovino mp','COZINHA','Congelada Cozinha','KG',37.3598),
('1876','filé de peito espalmado mp','COZINHA','Congelada Cozinha','KG',21.98),
('608','file de peito mp','COZINHA','Congelada Cozinha','KG',13.1),
('607','file de sobrecoxa mp','COZINHA','Congelada Cozinha','KG',12.35),
('1561','fraldinha mp','COZINHA','Congelada Cozinha','KG',36.8999),
('610','hamburguer angus 200gr mp','COZINHA','Congelada Cozinha','UND',11.6646),
('611','hamburguer bovino 120gr mp','COZINHA','Congelada Cozinha','UND',0.6662),
('1877','isca de frango mp','COZINHA','Congelada Cozinha','KG',22.8),
('553','linguiça calabresa mp','COZINHA','Congelada Cozinha/Resfriada Cozinha','KG',20.0),
('554','linguiça toscana mp','COZINHA','Congelada Cozinha','KG',12.87),
('1870','lombo fresco mp','COZINHA','Congelada Cozinha','KG',16.01),
('614','lombo salgado mp','COZINHA','Congelada Cozinha','KG',22.9701),
('558','manta de bacon mp','COZINHA','Resfriada Cozinha','KG',28.7),
('1335','pé de porco mp','COZINHA','Congelada Cozinha','KG',13.0),
('574','peperoni mp','COZINHA','Congelada Cozinha','KG',76.41),
('1355','pernil suino resfriado mp','COZINHA','Congelada Cozinha','KG',18.99),
('612','picanha mp','COZINHA','Congelada Cozinha','KG',64.9797),
('576','presunto mp','COZINHA','Congelada Cozinha','KG',23.92),
('1336','rabo de porco mp','COZINHA','Congelada Cozinha','KG',26.0),
('1318','amstel lata mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar','UND',3.8373),
('890','amstel long neck mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',5.6742),
('716','amstel ultra long neck mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',6.6825),
('411','budweiser long neck mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',3.6608),
('404','cerveja amstel 600ml mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',8.0838),
('1570','cerveja eisenbahn 600.mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',6.75),
('406','cerveja heineken 600ml mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',11.6931),
('405','cerveja original 600ml mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',5.9369),
('1166','corona lata mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',3.3338),
('412','corona long neck mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',5.6771),
('408','heineken 0 long neck mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',8.7546),
('1167','heineken lata mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',3.6481),
('409','heineken long neck mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',8.9079),
('1455','ORIGINAL LATA 269ML','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',2.8585),
('1786','skol beats lata','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',4.8622),
('734','skol beats long neck mp','BAR','Bar Central/Bar Areia/Estoque Areia/Resfriada Bar/Bar Camarote','UND',6.1694),
('1472','barril amstel 50l mp','BAR','Bares','LT',15.3691),
('1473','barril heineken 50l mp','BAR','Bares','UND',1061.19),
('1487','gás chopp mp','BAR','Bares','UND',29.9),
('1927','gelo mp','BAR','Congelada Bar','PCT',3.0),
('646','abacaxi congelado mp','BAR','Bar Molhado/BarCamarote/Bar Central/Congelada Bar','UND',2.6),
('664','açaí mp','BAR','Frezer Amarelo','KG',17.9),
('647','amora congelado mp','BAR','Bar Molhado/BarCamarote/Bar Central/Congelada Bar','UND',4.66),
('1555','anel de cebola mp','COZINHA','Congelada Cozinha','KG',19.303),
('513','batata canoa mp','COZINHA','Congelada Cozinha','KG',19.3033),
('515','batata palito mp','COZINHA','Congelada Cozinha','KG',17.5016),
('1707','bolinho de carne mp','COZINHA','Congelada Cozinha','UND',1.09),
('1084','bolinho de queijo mp','COZINHA','Congelada Cozinha','UND',0.48),
('649','caju congelado mp','BAR','Bar Molhado/BarCamarote/Bar Central/Congelada Bar','UND',4.59),
('657','camarao cinza limpo 40/60 mp','COZINHA','Congelada Cozinha','KG',88.6),
('1081','coco congelado mp','BAR','Bar Molhado/BarCamarote/Bar Central/Congelada Bar','UND',2.93),
('1562','conchiglione 4 queijos mp','COZINHA','Congelada Cozinha','KG',40.0),
('1924','file de panga mp','COZINHA','Congelada Cozinha','KG',23.8),
('650','frutas vermelhas mp','BAR','Bar Molhado/BarCamarote/Bar Central/Congelada Bar','UND',4.29),
('652','maracuja congelado mp','BAR','Bar Molhado/BarCamarote/Bar Central/Congelada Bar','UND',5.2),
('653','morango congelado mp','BAR','Bar Molhado/BarCamarote/Bar Central/Congelada Bar','UND',2.85),
('1481','nhoque mp','COZINHA','Congelada Cozinha','KG',24.0),
('655','pastel carne mp','COZINHA','Resfriada Cozinha','UND',2.2),
('656','pastel queijo mp','COZINHA','Resfriada Cozinha','UND',2.2),
('718','petit gateau mp','COZINHA','Frezer Amarelo','UND',6.6667),
('1556','polenta mp','COZINHA','Congelada Cozinha','KG',16.393),
('1640','risoli mp','COZINHA','Congelada Cozinha','UND',1.02),
('775','sorvete de chocolate mp','BAR','Frezer Amarelo','KG',12.1429),
('720','sorvete de creme mp','COZINHA','Frezer Amarelo','KG',11.4286),
('774','sorvete de morango mp','BAR','Frezer Amarelo','KG',11.4286),
('658','tilapia mp','COZINHA','Congelada Cozinha','KG',44.5),
('654','uva congelado mp','BAR','Bar Molhado/BarCamarote/Bar Central/Congelada Bar','UND',3.24),
('1643','coca cola 2 litros mp','BAR','Resfriada Bar/Estoque Areia','UND',9.2867),
('1129','GUARANA 2L D','BAR','Resfriada Bar/Estoque Areia','UND',5.48),
('1871','sprite 2 litros mp','BAR','Resfriada Bar/estoque Areia','UND',1.3973),
('1698','to go respiro P ref. 313 mp','COZINHA','Estoque Central','UND',1.272),
('1884','barquinha kraft','COZINHA','Estoque Central','UND',0.472),
('1416','bobina impressora','ADM','Estoque Central','UND',104.45),
('1390','caixa colher 20x50','SALÃO','Estoque Central','UND',6.46),
('1969','caixa de pizza.mp','COZINHA','Estoque Central','UND',2.1596),
('1435','canudo flexível','BAR','Estoque Central','UND',0.0671),
('1436','canudo mexedor','BAR','Estoque Central','UND',0.1293),
('1483','filme pvc','COZINHA','Estoque Central','UND',56.78),
('1905','garfo sobremesa','SALÃO','Estoque Central','UND',38.91),
('1420','guardanapos','SALÃO','Estoque Central','UND',0.076),
('1906','kit talheres','SALÃO','Estoque Central','UND',27.6),
('1485','luva de limpeza','LIMPEZA','Estoque Limpeza','UND',9.81),
('1398','luva nitrlica','LIMPEZA','Estoque Limpeza','UND',29.92),
('1401','pano multiuso perflex','LIMPEZA','Estoque Limpeza','UND',67.72),
('1402','papel higienico rolão','LIMPEZA','Estoque Limpeza','UND',8.9462),
('1403','papel toalha rolão','LIMPEZA','Estoque Limpeza','UND',12.9688),
('1486','potinho de molho','COZINHA','Estoque Central','UND',0.23),
('1441','pratinho de bolo','SALÃO','Estoque Central','UND',78.56),
('1423','saco de gelo','BAR','Congelada Bar','PCT',3.0),
('1407','saco para lixo 100l reforçado','LIMPEZA','Estoque Limpeza','PCT',63.45),
('1408','saco para lixo 40l','LIMPEZA','Estoque Limpeza','PCT',15.87),
('1410','tela de mictório','LIMPEZA','Estoque Limpeza','PCT',3.34),
('1411','touca descartavel inoven','COZINHA','Estoque Limpeza','PCT',10.79),
('1442','vela estrelinha','SALÃO','Recepção','UND',4.48),
('510','bala de goma mp','COZINHA','Estoque Central','KG',40.0),
('525','barra de chocolate ao leite mp','COZINHA','Estoque Central','KG',84.9048),
('528','bisnaga chocolate ao leite mp','COZINHA','Estoque Central','KG',23.9933),
('1343','bisnaga de avelã mp','COZINHA','Estoque Central','KG',33.3564),
('533','bisnaga doce de leite mp','COZINHA','Estoque Central','KG',14.6),
('518','bolacha oreo mp','COZINHA','Estoque Central','UND',44.0),
('524','chantily caixinha mp','COZINHA','Resfriada Cozinha','LT',19.29),
('1353','cobertura de morango mp','BAR','Estoque Central','KG',18.8),
('1959','granulado colorido mp','COZINHA','Estoque Central','KG',23.83),
('561','marshmellow mp','COZINHA','Estoque Central','KG',70.0),
('1916','gelo melancia mp','BAR','Bar Molhado','UND',1.0),
('1389','bobina picotada','COZINHA','Estoque Central','KG',27.14),
('1943','copo agua mp','SALÃO','Estoque Central','UND',0.4699),
('1942','copo cafe mp','SALÃO','Estoque Central','CX',40.92),
('1560','AVENTAL DESCARTAVEL','COZINHA','Estoque Central','UND',21.7),
('589','espetinho camarão mp','COZINHA','Congelada Cozinha','UND',5.6043),
('590','espetinho carne mp','COZINHA','Congelada Cozinha','UND',4.705),
('591','espetinho coração mp','COZINHA','Congelada Cozinha','UND',4.61),
('592','espetinho frango mp','COZINHA','Congelada Cozinha','UND',2.925),
('593','espetinho kafta mp','COZINHA','Congelada Cozinha','UND',3.5133),
('595','espetinho linguiça cuiabana mp','COZINHA','Congelada Cozinha','UND',4.5033),
('594','espetinho linguiça mp','COZINHA','Congelada Cozinha','UND',2.5733),
('596','espetinho medalhão bovino mp','COZINHA','Congelada Cozinha','UND',7.304),
('597','espetinho medalhão frango mp','COZINHA','Congelada Cozinha','UND',5.89),
('598','espetinho muss defumado mp','COZINHA','Congelada Cozinha','UND',3.942),
('601','espetinho queijo coalho mp','COZINHA','Resfriada Cozinha','UND',2.5),
('599','espetinho vegetariano mp','COZINHA','Congelada Cozinha','UND',4.642),
('600','pão de alho mp','COZINHA','Resfriada Cozinha','UND',2.378),
('1438','ARMINHA DE AGUA','ESPORTE','Esporte','UND',13.99),
('1307','BIQUINI INFANTIL','ESPORTE','Esporte','UND',50.0),
('1499','BIQUINI TOP','ESPORTE','Esporte','UND',40.0),
('902','BOIA','ESPORTE','Esporte','UND',15.99),
('1357','BOIA COLETE CINTURA','ESPORTE','Esporte','UND',55.0),
('1776','boia de braço 23x14','ESPORTE','Esporte','UND',8.45),
('1359','BOIA FRALDA','ESPORTE','Esporte','UND',19.99),
('963','BOIA REDONDA','ESPORTE','Esporte','UND',16.99),
('899','BOLA','ESPORTE','Esporte','UND',10.9),
('916','BOLA INFANTIL FTV','ESPORTE','Esporte','UND',4.19),
('1218','BOLA INFANTIL VOLEI','ESPORTE','Esporte','UND',33.99),
('898','CHAPEU','ESPORTE','Esporte','UND',0),
('921','COLETE','ESPORTE','Esporte','UND',60.0),
('1314','COPO STANLEY','ESPORTE','Esporte','UND',60.0),
('1437','FRALDA','ESPORTE','Esporte','UND',3.959),
('964','MACARRAO DE PISCINA','ESPORTE','Esporte','UND',7.28),
('915','OCULOS DE NATAÇÃO','ESPORTE','Esporte','UND',9.99),
('1937','OCULOS DE SOL','ESPORTE','Esporte','UND',0),
('1938','OCULOS ESPORTIVO','ESPORTE','Esporte','UND',0),
('901','PROTETOR SOLAR 30','ESPORTE','Esporte','UND',3.37),
('910','PROTETOR SOLAR 60','ESPORTE','Esporte','UND',30.072),
('1944','pulseiras identificaçao','ADM','Recepção','UND',0.18),
('894','SHORTS','ESPORTE','Esporte','UND',10.6667),
('1784','shorts infantil''','ESPORTE','Esporte','UND',0),
('895','SUNGA','ESPORTE','Esporte','UND',40.0),
('961','SUNGA INFANTIL','ESPORTE','Esporte','UND',51.33),
('904','TOALHA','ESPORTE','Esporte','UND',24.0633),
('1958','TOALHA DE ROSTO 48X80 KARSTEN','ESPORTE','Esporte','UND',0),
('986','TOUCA','ESPORTE','Esporte','UND',9.4),
('1161','bola de volei ativo','ESPORTE','Esporte','UND',11.7),
('1162','bola e futevolei ativo','ESPORTE','Esporte','UND',9.99),
('1165','bolinha beach tennis ativo','ESPORTE','Esporte','UND',10.5),
('1163','raquete ativo','ESPORTE','Esporte','UND',0),
('463','bag sake 5lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',28.58),
('1339','cachaça espirito de minas','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar AreiaEstoque Central','LT',1.0),
('1338','cachaça são franscisco mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar AreiaEstoque Central','LT',28.56),
('440','garrafa absolut 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',54.9),
('984','garrafa absolut elyx mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',402.9),
('469','garrafa absolut vanilia 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',83.8667),
('867','garrafa angostura mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',184.9),
('467','garrafa aperol 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',57.2),
('464','garrafa bacardi carta blanca mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',34.5918),
('447','garrafa ballantines 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',1.0),
('437','garrafa beefeater 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',86.5333),
('694','garrafa beefeater pin 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',112.7143),
('983','garrafa beefetater 24 mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',178.9),
('445','garrafa black label 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',149.9),
('1973','garrafa blue label 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',1720.0),
('1351','garrafa boazinha mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',41.6),
('461','garrafa busca vida 670ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',67.611),
('452','garrafa c. suavignon 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',29.2),
('704','garrafa campari 900ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',48.8889),
('932','garrafa chandon reser 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',1.0),
('449','garrafa chivas regal 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',117.901),
('1260','garrafa ciroc sabores mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',239.8667),
('762','garrafa cramberry 700ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',0.1),
('703','garrafa curaçau blue 720ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',57.5),
('693','garrafa domecq 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',1.0),
('457','garrafa don luiz 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',82.5333),
('462','garrafa gabriela 5lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',3.6),
('446','garrafa gold label 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',292.0),
('761','garrafa grenadine 700ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',71.2857),
('441','garrafa greygoose 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',146.5333),
('692','garrafa groselha 900ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',21.0),
('442','garrafa jack daniel''s 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',115.9),
('443','garrafa jack honey 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',143.9),
('458','garrafa jose cuervo 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',139.8693),
('695','garrafa kariri 960ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',18.0729),
('760','garrafa laranja azul 700ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',55.5714),
('456','garrafa licor 43 700ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',197.3),
('1212','garrafa licor 43 chocolate mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',238.6571),
('682','garrafa licor ballena 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',1.0),
('1095','garrafa malbec 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',21.23),
('688','garrafa malibu 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',43.9),
('1593','garrafa mioranza seco 750 ml','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',12.9),
('1592','garrafa mioranza suave 750','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',18.0267),
('864','garrafa morango 700ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',50.5333),
('448','garrafa old par 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',129.99),
('451','garrafa orloff 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',23.9),
('444','garrafa red label 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',71.0),
('455','garrafa rose piscine 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',0.1),
('1974','garrafa royal sallut mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',1142.7143),
('453','garrafa s. blanc 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',28.3067),
('468','garrafa salton moscatel 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',36.92),
('705','garrafa seagers 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','UND',34.87),
('459','garrafa seleta 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',0.1),
('439','garrafa smirnoff 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',26.89),
('465','garrafa stock peach 720ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',55.4167),
('863','garrafa tangerina 700ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',54.1429),
('438','garrafa tanqueray 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',119.8667),
('471','garrafa vinho branco suave 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',14.2133),
('470','garrafa vinho tinto suave 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',13.5867),
('450','garrafa velho barreiro 1lt mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',14.2758),
('466','garrafa vermuth 750ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',44.4667),
('1258','garrafa whisky buchanan´s mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',159.91),
('1308','garrafa whisky jameson 750ml','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',72.9),
('745','garrafa xarope lichia 700ml mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',57.0),
('1915','itubaina','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','LT',41.88),
('670','mel mp','BAR','Bar Molhado','LT',8.29),
('472','abacaxi mp','COZINHA','Resfriada Cozinha','KG',7.9),
('474','abobrinha mp','COZINHA','Resfriada Cozinha','KG',7.95),
('925','agriao mp','COZINHA','Resfriada Cozinha','KG',37.9615),
('708','alecrim mp','COZINHA','Resfriada Cozinha','KG',89.0),
('475','alface americana mp','COZINHA','Resfriada Cozinha','KG',23.08),
('476','alface crespa mp','COZINHA','Resfriada Cozinha','KG',24.81),
('477','alface crespa roxa mp','COZINHA','Resfriada Cozinha','KG',31.1769),
('478','alho descascado mp','COZINHA','Resfriada Cozinha','KG',23.25),
('479','banana nanica mp','COZINHA','Resfriada Cozinha','KG',6.9),
('945','batata asterix mp','COZINHA','Resfriada Cozinha','KG',11.6),
('480','batata bolinha mp','COZINHA','Resfriada Cozinha','KG',10.65),
('930','batata doce mp','COZINHA','Resfriada Cozinha','KG',6.0),
('481','batata lavada mp','COZINHA','Resfriada Cozinha','KG',10.95),
('482','beringela mp','COZINHA','Resfriada Cozinha','KG',12.25),
('483','beterraba mp','COZINHA','Resfriada Cozinha','KG',18.38),
('1970','beterraba ralada.mp','COZINHA','Resfriada Cozinha','KG',0),
('868','brocolis mp','COZINHA','Resfriada Cozinha','KG',25.25),
('959','cana mp','BAR','Resfriada Bar','KG',18.75),
('484','cebola branca mp','COZINHA','Resfriada Cozinha','KG',6.75),
('485','cebola roxa mp','COZINHA','Resfriada Cozinha','KG',10.25),
('486','cebolinha mp','COZINHA','Resfriada Cozinha','KG',29.8462),
('487','cenoura mp','COZINHA','Resfriada Cozinha','KG',10.5),
('1971','cenoura ralada.mp','COZINHA','Resfriada Cozinha','KG',12.8),
('1100','chuchu mp','COZINHA','Resfriada Cozinha','KG',6.0),
('773','coco verde mp','BAR','Resfriada Bar','UND',3.9),
('488','coentro mp','COZINHA','Resfriada Cozinha','KG',41.0),
('869','couve flor mp','COZINHA','Resfriada Cozinha','KG',34.95),
('489','couve mp','COZINHA','Resfriada Cozinha','KG',21.26),
('771','flor comestivel mp','BAR','Resfriada Bar','UND',7.2727),
('770','gengibre mp','BAR','Resfriada Bar','KG',11.2),
('709','hortelã mp','BAR','Resfriada Bar','KG',19.0),
('1645','laranja bahia mp','BAR','Resfriada Bar','KG',14.95),
('706','laranja mp','BAR','Resfriada Bar','KG',0.1875),
('746','lichia em lata mp','BAR','Estoque Central/Bar Molhado','KG',98.52),
('711','lima da persia mp','BAR','Resfriada Bar','KG',15.3),
('707','limao mp','BAR','Resfriada Bar','KG',3.75),
('710','limão siciliano mp','BAR','Resfriada Bar','KG',14.7),
('1104','mamao mp','COZINHA','Resfriada Cozinha','UND',9.0),
('648','mandioca congelada mp','COZINHA','Congelada Cozinha','KG',7.0),
('490','manjericão mp','COZINHA','Resfriada Cozinha','KG',80.0),
('1138','melancia mp','COZINHA','Resfriada Cozinha','KG',4.2),
('1178','melao mp','COZINHA','Resfriada Cozinha','KG',7.65),
('712','mexerica mp','BAR','Resfriada Bar','KG',7.4),
('1880','mini frize roxa mp','COZINHA','Resfriada Cozinha','KG',31.1769),
('1881','mix marsala mp','COZINHA','Resfriada Cozinha','KG',15.73),
('713','morango mp','BAR','Resfriada Bar','KG',52.0),
('491','ovo mp','COZINHA','Resfriada Cozinha','UND',1.875),
('492','pepino mp','COZINHA','Resfriada Cozinha','KG',13.45),
('493','pimenta dedo moça mp','COZINHA','Resfriada Cozinha','KG',21.0),
('494','pimentao amarelo mp','COZINHA','Resfriada Cozinha','KG',18.2),
('495','pimentao verde mp','COZINHA','Resfriada Cozinha','KG',12.9),
('496','pimentao vermelho mp','COZINHA','Resfriada Cozinha','KG',21.0),
('498','salsão mp','COZINHA','Resfriada Cozinha','KG',13.9),
('499','salsinha mp','COZINHA','Resfriada Cozinha','KG',26.5),
('500','shimeji mp','COZINHA','Resfriada Cozinha','KG',52.0),
('501','shitake mp','COZINHA','Resfriada Cozinha','KG',52.0),
('502','tomate carmen mp','COZINHA','Resfriada Cozinha','KG',15.6),
('503','tomate cereja mp','COZINHA','Resfriada Cozinha','KG',27.9),
('504','tomate italiano mp','COZINHA','Resfriada Cozinha','KG',11.65),
('505','vagem mp','COZINHA','Resfriada Cozinha','KG',25.2),
('1855','produção arroz','COZINHA','Resfriada Cozinha','KG',7.643),
('1980','produção calabresa pizza','COZINHA','Congelada Cozinha','KG',0),
('1953','produção catupiry empanado','COZINHA','Congelada Cozinha','KG',0),
('1168','produção cebola temperada','COZINHA','Resfriada Cozinha','KG',5.74),
('1952','produção chocoburguer','COZINHA','Congelada Cozinha','KG',0),
('1471','produção dadinho de tapioca','COZINHA','Resfriada Cozinha','UND',0.33),
('1954','produção de almondegas','COZINHA','Congelada Cozinha','KG',0),
('1712','produção frango pizza','COZINHA','Congelada Cozinha','KG',0),
('763','produção farofa','COZINHA','Resfriada Cozinha','KG',13.91),
('729','produção farofa de bacon','COZINHA','Resfriada Cozinha','KG',0),
('1951','produção file tilapia','COZINHA','Congelada Cozinha','KG',0),
('1949','produção frango a passarinho','COZINHA','Congelada Cozinha','KG',16.9802),
('1789','produção isca de frango','COZINHA','Congelada Cozinha','KG',22.8),
('1950','produção isca de peixe','COZINHA','Congelada Cozinha','KG',0),
('725','produção maionese de coentro','COZINHA','Resfriada Cozinha','LT',0),
('730','produção maionese siriracha','COZINHA','Resfriada Cozinha','LT',0),
('752','produção massa de pizza','COZINHA','Resfriada Cozinha','KG',0),
('1978','produção mix cogumelo','COZINHA','Congelada Cozinha','KG',0),
('934','produção molho branco','COZINHA','Resfriada Cozinha','LT',0),
('732','produção molho de tomate','COZINHA','Congelada Cozinha','LT',0),
('728','produção molho gorgonzola','COZINHA','Resfriada Cozinha','LT',4.91),
('724','produção molho pesto','COZINHA','Resfriada Cozinha','LT',0),
('788','produção pasta de pimentão','COZINHA','Resfriada Cozinha','LT',0),
('754','produção pure de batata','COZINHA','Congelada Cozinha','KG',0),
('1526','produção pure de mandioca','COZINHA','Congelada Cozinha','KG',0),
('1977','produção smoke','COZINHA','Congelada Cozinha','KG',0),
('1875','produção sumo de laranja','BAR','Bar Central','LT',0),
('1874','produção sumo de limão','BAR','Bar Central','LT',0),
('756','produção taça chocolate','COZINHA','Resfriada Cozinha','LT',137.68),
('1955','produção tempero base proteina','COZINHA','Resfriada Cozinha','KG',0),
('1879','produção tilapia fish','COZINHA','Congelada Cozinha','KG',41.9),
('1979','produção torresmo','COZINHA','Congelada Cozinha','KG',0),
('727','produção vinagrete','COZINHA','Resfriada Cozinha','KG',0),
('1210','produção xarope de gengibre','BAR','Bar Molhado','LT',0),
('1211','produção xarope de morango','BAR','Bar Molhado','LT',0),
('1430','alcool gel','LIMPEZA','Estoque Limpeza','UND',24.86),
('1388','alcool liquido','LIMPEZA','Estoque Limpeza','UND',6.74),
('1965','balde de limpeza','LIMPEZA','Estoque Limpeza','UND',15.35),
('1414','candida','LIMPEZA','Estoque Limpeza','UND',9.79),
('1387','desinfetante','LIMPEZA','Estoque Limpeza','UND',81.11),
('1434','detergente máquina de lavar','LIMPEZA','Estoque Limpeza','UND',423.0),
('1392','detergente neutro 5l','LIMPEZA','Estoque Limpeza','UND',16.6),
('1966','dispenser papel higienico.mp','LIMPEZA','Estoque Limpeza','UND',67.07),
('1393','esponja multiuso','LIMPEZA','Estoque Limpeza','UND',1.87),
('1394','fibra de limpeza fibraço','LIMPEZA','Estoque Limpeza','UND',12.22),
('1889','glp a granel mp','COZINHA','Recepção','KG',8.3287),
('1395','lã de aço - bombril','LIMPEZA','Estoque Limpeza','UND',2.51),
('1397','lustra movel','LIMPEZA','Estoque Limpeza','UND',8.02),
('1400','naftalina','LIMPEZA','Estoque Limpeza','UND',3.33),
('1968','palha de aço.mp','LIMPEZA','Estoque Limpeza','UND',1.45),
('1967','rodo limpeza','LIMPEZA','Estoque Limpeza','UND',9.07),
('1404','sabão em pó','LIMPEZA','Estoque Limpeza','UND',11.89),
('1433','sabonete liquido','LIMPEZA','Estoque Limpeza','UND',24.91),
('1413','vassoura multi-uso','LIMPEZA','Estoque Limpeza','PCT',12.59),
('1885','vipar pan','LIMPEZA','Estoque Limpeza','LT',20.276),
('1886','viper max','LIMPEZA','Estoque Limpeza','LT',17.202),
('1865','alcatra mp','COZINHA','Congelada Cozinha','KG',54.2),
('506','açucar mp','BAR','Estoque Central','KG',2.908),
('697','açucar sache mp','SALÃO','Estoque Central','UND',0.0182),
('862','adoçante liquido mp','SALÃO','Estoque Central','UND',7.0575),
('1801','alho em po mp','COZINHA','Estoque Central','KG',39.0),
('1804','alho frito mp','COZINHA','Estoque Central','KG',62.0),
('1581','amaciante de carne mp','COZINHA','Estoque Central','KG',8.64),
('1508','amendoas defumadas mp','COZINHA','Estoque Central','KG',120.0),
('1131','amido de milho mp','COZINHA','Estoque Central','KG',5.98),
('507','arroz mp','COZINHA','Estoque Central','KG',3.85),
('1644','arroz parbolizado mp','COZINHA','Estoque Central','KG',21.99),
('951','atum mp','COZINHA','Resfriada Cozinha','KG',74.4),
('508','azeite composto mp','COZINHA','Estoque Central','LT',10.576),
('702','azeite sache mp','SALÃO','Estoque Central','UND',0.3096),
('509','azeitona preta mp','COZINHA','Estoque Central','KG',34.995),
('511','barbecue mp','COZINHA','Estoque Central','KG',11.1314),
('521','bisnaga catupiry mp','COZINHA','Resfriada Cozinha','KG',29.2828),
('516','bisnaga cheddar mp','COZINHA','Resfriada Cozinha','KG',35.26),
('531','bisnaga cream cheese mp','COZINHA','Resfriada Cozinha','KG',32.6833),
('907','bisnaga de chocolate branco mp','COZINHA','Estoque Central','UND',21.99),
('1963','bolo eventos.mp','COZINHA','Estoque Central','UND',26.0),
('519','café mp','COZINHA','Estoque Central','KG',38.766),
('888','canelone 4Q mp','COZINHA','Congelada Cozinha','KG',26.0),
('1554','carvao mp','COZINHA','Estoque Central','PCT',21.0),
('698','catchup sache mp','SALÃO','Estoque Central','UND',0.1458),
('1802','cebola em po','COZINHA','Estoque Central','KG',45.0),
('522','cebolinha em conserva mp','COZINHA','Estoque Central','KG',20.565),
('776','cha de morango mp','BAR','Estoque Central/Bar Molhado/Bar Camarote/Bar Areia','UND',0.604),
('1809','chimichurri','COZINHA','Estoque Central','KG',69.0),
('719','cobertura de chocolate mp','COZINHA','Estoque Central','UND',26.19),
('529','coco ralado mp','COZINHA','Estoque Central','KG',86.4),
('821','coxinha mp','COZINHA','Congelada Cozinha','UND',0.6097),
('532','creme de leite mp','COZINHA','Estoque Central','KG',12.8313),
('536','farinha de mandioca fina mp','COZINHA','Estoque Central','KG',27.56),
('537','farinha de trigo mp','COZINHA','Estoque Central','KG',3.052),
('538','farinha de trigo pizza mp','COZINHA','Estoque Central','KG',3.998),
('539','farinha panko mp','COZINHA','Estoque Central','KG',14.2),
('540','feijão carioca mp','COZINHA','Estoque Central','KG',10.536),
('1083','feijao fradinho mp','COZINHA','Estoque Central','KG',8.266),
('541','feijão preto mp','COZINHA','Estoque Central','KG',6.97),
('542','fermento biológico fresco mp','LIMPEZA','Estoque Central','KG',31.72),
('543','fermento quimico em pó mp','LIMPEZA','Estoque Central','KG',40.8),
('1883','fondor mp','LIMPEZA','Estoque Central','KG',32.25),
('946','fuba mp','LIMPEZA','Estoque Central','KG',7.7),
('923','galão de oleo mp','LIMPEZA','Estoque Central','LT',8.0183),
('735','galao sweet chili sauce mp','LIMPEZA','Estoque Central','LT',32.2222),
('1509','glutamato monossodico mp','LIMPEZA','Estoque Central','KG',27.1),
('546','granola mp','LIMPEZA','Estoque Central','KG',44.58),
('947','grao de bico mp','LIMPEZA','Estoque Central','KG',36.49),
('548','ketchup mp','LIMPEZA','Estoque Central','KG',15.51),
('549','leite condensado mp','LIMPEZA','Estoque Central/Bar Molhado','KG',14.4051),
('550','leite de coco mp','LIMPEZA','Estoque Central','LT',2.5958),
('552','leite em pó mp','LIMPEZA','Estoque Central','KG',31.77),
('551','leite integral mp','LIMPEZA','Estoque Central','LT',5.2183),
('1803','lemon pepper mp','LIMPEZA','Estoque Central','KG',59.24),
('1806','louro folhas mp','LIMPEZA','Estoque Central','KG',0),
('555','macarrão n8 mp','LIMPEZA','Estoque Central','KG',6.1767),
('1577','macarrão penne mp','LIMPEZA','Estoque Central','KG',5.5889),
('557','maionese mp','LIMPEZA','Estoque Central','KG',16.6633),
('699','maionese sache mp','LIMPEZA','Estoque Central','UND',0.1319),
('559','manteiga mp','LIMPEZA','Resfriada Cozinha','KG',48.0),
('1136','massa de lasanha mp.','LIMPEZA','Congelada Cozinha','KG',18.5),
('563','molho de pimenta mp','LIMPEZA','Estoque Central','LT',61.8556),
('871','molho shoyu mp','LIMPEZA','Estoque Central','LT',20.442),
('564','molho tarê mp','LIMPEZA','Estoque Central','LT',10.516),
('565','mostarda mp','LIMPEZA','Estoque Central','KG',8.8394),
('1706','mostarda sache mo','LIMPEZA','Estoque Central','UND',0.14),
('1200','nozes mp','COZINHA','Estoque Central','KG',0),
('568','oleo de soja mp','COZINHA','Estoque Central','LT',7.6422),
('1922','oregano mp','COZINHA','Estoque Central','KG',60.0),
('569','ovo de codorna cozido mp','COZINHA','Resfriada Cozinha','KG',29.1),
('571','palmito inteiro vidro mp','COZINHA','Estoque Central','KG',19.8333),
('660','pao australiano mp','COZINHA','Congelada Cozinha','UND',1.8667),
('661','pao ciabata mp','COZINHA','Congelada Cozinha','UND',5.6302),
('662','pao hambuguer brioche 64g mp','COZINHA','Congelada Cozinha','UND',1.8),
('1808','paprica defumada mp','COZINHA','Estoque Central','KG',24.0),
('575','pímenta biquinho mp','COZINHA','Estoque Central','KG',20.54),
('1345','pimenta calabresa mp','COZINHA','Estoque Central','LT',49.0),
('577','queijo brie mp','COZINHA','Resfriada Cozinha','KG',71.12),
('579','queijo cheddar fatiado mp','COZINHA','Resfriada Cozinha','UND',0.4439),
('1259','queijo coalho mp','COZINHA','Resfriada Cozinha/Congelada Cozinha','KG',38.9),
('578','queijo gorgonzola mp','COZINHA','Resfriada Cozinha/congelada Cozinha','KG',58.7496),
('580','queijo mussarela fatiada mp','COZINHA','Resfriada Cozinha','KG',0.544),
('581','queijo mussarela mp','COZINHA','Resfriada Cozinha/congelada Cozinha','KG',35.99),
('582','queijo parmesão mp','COZINHA','Resfriada Cozinha/congelada Cozinha','KG',62.19),
('583','queijo provolone mp','COZINHA','Resfriada Cozinha/congelada Cozinha','KG',52.5608),
('669','rapadura mp','BAR','Bar Molhado','KG',16.0),
('887','rondelle mp','COZINHA','Congelada Cozinha','KG',30.0),
('1972','sache pimenta mp','SALÃO','Estoque Central','UND',0.1474),
('584','sal grosso mp','COZINHA','Estoque Central','KG',2.99),
('585','sal refinado mp','COZINHA','Estoque Central','KG',2.52),
('701','sal sache mp','SALÃO','Estoque Central','UND',23.23),
('1921','salsa desidratada mp','COZINHA','Estoque Central','KG',44.0),
('1689','suco del vale goiaba mp','BAR','Resfriada Bar','UND',0.5483),
('1688','suco del vale maracujá mp','BAR','Resfriada Bar','UND',3.58),
('1690','suco del vale pessego mp','BAR','Resfriada Bar','UND',3.58),
('1691','suco del vale uva mp','BAR','Resfriada Bar','UND',3.58),
('1354','tapioca granulada mp','COZINHA','Estoque Central','KG',25.0),
('566','tortilhas mp','COZINHA','Estoque Central','KG',33.6),
('588','vinagre mp','COZINHA','Estoque Central','UND',3.9917),
('700','vinagre sache mp','SALÃO','Estoque Central','UND',0.2192),
('1913','farinha de milho mp','COZINHA','Estoque Central','UND',5.34),
('421','agua com gas mp','BAR','Bar Central/Estoque Areia/Bar Molhado/Bar Areia/Bar Camarote/Estoque Central','UND',1.89),
('717','agua sem gas 1,5lt mp','ESPORTE','Esporte/Estoque Areia','UND',2.9983),
('420','agua sem gas mp','BAR','Bar Central/Estoque Areia/Bar Areia/Bar Camarote/Estoque Central','UND',1.985),
('423','coca cola mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',3.1485),
('424','coca cola zero mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',3.1356),
('1575','Emusificante','BAR','Bar Molhado','KG',33.33),
('1208','energético bally melancia mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',7.89),
('1205','energético bally tropical mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',8.2),
('431','fanta laranja mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',2.5472),
('430','fanta uva mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',2.5472),
('422','gatorade mp','ESPORTE','Esporte/Estoque Areia','UND',4.7483),
('432','gelo de coco mp','BAR','Bar Molhado/Congelada Bar','UND',1.0),
('425','guarana mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',2.0567),
('426','guarana zero mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',2.5283),
('1305','h2o limoneto mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',3.8335),
('1304','h2o mp','BAR','Bar Central/Bar Camarote/Estoque Areia/Bar Areia/Bar Camarote','UND',3.8133),
('1904','powerrade mountain mp','ESPORTE','Esporte','UND',3.4317),
('767','red bull melancia mp','BAR','Bar Molhado/ Bar Camarote/Bar Areia/Resfriada Bar/Estoque Central','UND',6.8468),
('433','red bull mp','BAR','Bar Molhado/ Bar Camarote/Bar Areia/Resfriada Bar/Estoque Central','UND',6.8468),
('768','red bull tropical mp','BAR','Bar Molhado/ Bar Camarote/Bar Areia/Resfriada Bar/Estoque Central','UND',6.8468),
('1721','red bull zero mp','BAR','Bar Molhado/ Bar Camarote/Bar Areia/Resfriada Bar/Estoque Central','UND',7.7005),
('428','schweppes citrus mp','BAR','Bar Molhado/ Bar Camarote/Bar Areia/Resfriada Bar/Estoque Central/ Bar Central','UND',3.1479),
('427','sprite mp','BAR','Bar Central/Bar Molhado/ Bar Camarote/Bar Areia/Resfriada Bar/Estoque Central/Estoque Areia','UND',2.91),
('1894','suco dell vale manga mp','BAR','Bar Central','UND',3.58),
('733','tonica fys mp','BAR','Bar Central/Bar Molhado/ Bar Camarote/Bar Areia/Resfriada Bar/Estoque Central/Estoque Areia','UND',4.0708),
('429','tonica mp','BAR','Bar Central/Bar Molhado/ Bar Camarote/Bar Areia/Resfriada Bar/Estoque Central/Estoque Areia','UND',3.79),
('1946','vinho chalise br.seco 750ml mp','BAR','Bar Molhado/Estoque Central','LT',16.275),
('671','PRODUTOS NÃO USADOS','ADM','Recepção','UND',8.19)
ON CONFLICT (codigo) DO UPDATE SET nome=EXCLUDED.nome, classificacao=EXCLUDED.classificacao, setor=EXCLUDED.setor, unidade=EXCLUDED.unidade, custo=EXCLUDED.custo;
